seed = 13
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
path = ":data/breast_cancer"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[model]
depth = 3
heads = 8
attentiontype = "colrow"
dim = 24
dim_head = 30
ffn_mult = 1.7564330326604605
attn_dropout = 0.21182739966945235
ff_dropout = 0.32294705653332806

[optimizer]
type = "AdamW"
lr = 7.50195444362012e-05
weight_decay = 5.846326121643419e-06
