seed = 10
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
path = ":data/heart"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 0.00012520653814999459
weight_decay = 0.0

[model]
d_token = 216
n_blocks = 2
attention_dropout = 0.32294705653332806
ffn_d_hidden_factor = 1.5418410854134605
ffn_dropout = 0.4458865003910399
residual_dropout = 0.0
