seed = 6

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
cache = true
path = ":data/breast_cancer"
y_policy = "__null__"

[model]
iterations = 4000
od_pval = 0.001
bagging_temperature = 0.2653894909394454
depth = 9
l2_leaf_reg = 1.0300110565085727
leaf_estimation_iterations = 6
learning_rate = 0.6136045802294308
task_type = "CPU"
thread_count = 4

[fit]
early_stopping_rounds = 200
logging_level = "Verbose"
