seed = 5
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
path = ":data/stroke"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[model]
depth = 2
heads = 8
attentiontype = "colrow"
dim = 16
dim_head = 35
ffn_mult = 2.314448939499482
attn_dropout = 0.33342128386568726
ff_dropout = 0.02892417105342246

[optimizer]
type = "AdamW"
lr = 0.00014026790293244953
weight_decay = 5.2229470987692394e-05
