seed = 8
neighbors = "__null__"

[data]
seed = 0
num_policy = "__null__"
cache = true
path = ":data/pima"
cat_policy = "__null__"
y_policy = "__null__"

[model]
booster = "gbtree"
n_estimators = 4000
n_jobs = 1
tree_method = "hist"
use_label_encoder = false
colsample_bytree = 0.678370636354985
gamma = 0
lambda = 0.0
learning_rate = 0.014628569421376187
max_depth = 3
min_child_weight = 1.2382206514996652
subsample = 0.9144157510980826

[fit]
early_stopping_rounds = 200
verbose = true
