seed = 3
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
path = ":data/heart"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[model]
num_embeddings = "__null__"
d_main = 104
context_dropout = 0.19204103974104086
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.011725945422020555
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.00043952560337609173
weight_decay = 7.264261756198796e-06
