seed = 10
batch_size = 256
patience = 16
n_epochs = inf

[data]
seed = 0
cache = true
path = ":data/heart"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 9.024990788689462e-05
weight_decay = 0.0

[model]
num_embeddings = "__null__"

[model.backbone]
type = "MLP"
n_blocks = 2
d_layer = 799
dropout = 0.1290402306024396
activation = "ReLU"
