seed = 11

[data]
seed = 0
num_policy = "quantile"
cat_policy = "__null__"
cache = true
path = ":data/stroke"
y_policy = "__null__"

[model]
iterations = 4000
od_pval = 0.001
bagging_temperature = 0.6176354970758771
depth = 7
l2_leaf_reg = 9.637075956246598
leaf_estimation_iterations = 10
learning_rate = 0.06930456675054711
task_type = "CPU"
thread_count = 4

[fit]
early_stopping_rounds = 200
logging_level = "Verbose"
